### ISSUE TITLE
启动这个案例，会报错

### ISSUE THREAD

**Issue by seanin** [starts2000/ElectronQQLogin#5]
![1](https://user-images.githubusercontent.com/5111701/35082952-6faf1e80-fc57-11e7-8989-f900423de76d.jpg)

**Comment by seanin** [comment]
@starts2000

**Comment by starts2000** [comment]
参考http://www.cnblogs.com/Starts_2000/p/electron-ffi.html，重新编译下FFI试试

**Comment by seanin** [comment]
重新编译，下载也一直出错，

**Comment by starts2000** [comment]
可以参考文章里面提供的那个链接，里面有详细的介绍，如果还是有问题，可以先把FFI相关的代码先注释，不使用FFI应该是没什么问题的

**Comment by seanin** [comment]
我看着github ffi上面的配置npm，一直报错，装不了；国内网络装不了？ 我主要就是想用读取dll文件，这要用到ffi吧

**Comment by starts2000** [comment]
是的，使用DLL是需要用FFI的

**Comment by seanin** [comment]
好吧
